import { Subscription } from '@/components/cards/subscription-card';

export const subscriptionStorageKey = 'subscription-tracker-india-items-v1';

export const subscriptionCategories = [
  { id: 'all', label: 'All Services' },
  { id: 'entertainment', label: 'Entertainment' },
  { id: 'music', label: 'Music' },
  { id: 'shopping', label: 'Shopping' },
  { id: 'food', label: 'Food' },
  { id: 'fitness', label: 'Fitness' },
  { id: 'learning', label: 'Learning' },
  { id: 'other', label: 'Other' },
];

export const initialIndianSubscriptions: Subscription[] = [
  {
    id: '1',
    name: 'JioHotstar Premium',
    category: 'entertainment',
    cost: 299,
    currency: '₹',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-15',
    icon: '⭐',
    isActive: true,
    startedDate: '2025-02-20',
    paymentMethod: 'UPI autopay',
    reminderDays: 3,
    notes: 'Cricket, films, and family streaming plan.',
    website: 'https://www.hotstar.com',
  },
  {
    id: '2',
    name: 'YouTube Premium India',
    category: 'entertainment',
    cost: 149,
    currency: '₹',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-10',
    icon: '▶️',
    isActive: true,
    startedDate: '2024-11-10',
    paymentMethod: 'HDFC credit card',
    reminderDays: 2,
    notes: 'Ad-free YouTube plus YouTube Music.',
    website: 'https://www.youtube.com/premium',
  },
  {
    id: '3',
    name: 'Amazon Prime India',
    category: 'shopping',
    cost: 1499,
    currency: '₹',
    billingCycle: 'yearly',
    nextBillingDate: '2026-08-02',
    icon: '📦',
    isActive: true,
    startedDate: '2023-08-02',
    paymentMethod: 'ICICI credit card',
    reminderDays: 10,
    notes: 'Prime Video, shopping benefits, and Prime Music.',
    website: 'https://www.amazon.in/prime',
  },
  {
    id: '4',
    name: 'SonyLIV Premium',
    category: 'entertainment',
    cost: 999,
    currency: '₹',
    billingCycle: 'yearly',
    nextBillingDate: '2026-07-21',
    icon: '🏏',
    isActive: true,
    startedDate: '2025-07-21',
    paymentMethod: 'UPI autopay',
    reminderDays: 7,
    notes: 'Sports and Indian originals.',
    website: 'https://www.sonyliv.com',
  },
  {
    id: '5',
    name: 'ZEE5 Premium',
    category: 'entertainment',
    cost: 699,
    currency: '₹',
    billingCycle: 'yearly',
    nextBillingDate: '2026-09-05',
    icon: '🎬',
    isActive: true,
    startedDate: '2025-09-05',
    paymentMethod: 'SBI debit card',
    reminderDays: 7,
    notes: 'Hindi and regional films.',
    website: 'https://www.zee5.com',
  },
  {
    id: '6',
    name: 'Swiggy One',
    category: 'food',
    cost: 149,
    currency: '₹',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-03',
    icon: '🍽️',
    isActive: true,
    startedDate: '2026-01-03',
    paymentMethod: 'UPI autopay',
    reminderDays: 1,
    notes: 'Food delivery and Instamart savings.',
    website: 'https://www.swiggy.com/one',
  },
  {
    id: '7',
    name: 'Zomato Gold',
    category: 'food',
    cost: 99,
    currency: '₹',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-18',
    icon: '🍛',
    isActive: true,
    startedDate: '2026-02-18',
    paymentMethod: 'UPI autopay',
    reminderDays: 1,
    notes: 'Dining and delivery offers.',
    website: 'https://www.zomato.com/gold',
  },
  {
    id: '8',
    name: 'JioSaavn Pro',
    category: 'music',
    cost: 99,
    currency: '₹',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-24',
    icon: '🎧',
    isActive: true,
    startedDate: '2025-12-24',
    paymentMethod: 'Axis credit card',
    reminderDays: 2,
    notes: 'Offline music and ad-free listening.',
    website: 'https://www.jiosaavn.com/pro',
  },
  {
    id: '9',
    name: 'Tata Play Binge',
    category: 'entertainment',
    cost: 349,
    currency: '₹',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-28',
    icon: '📺',
    isActive: false,
    startedDate: '2025-10-28',
    paymentMethod: 'Tata Play wallet',
    reminderDays: 3,
    notes: 'Paused while comparing OTT bundles.',
    website: 'https://www.tataplaybinge.com',
  },
  {
    id: '10',
    name: 'Cult.fit Elite',
    category: 'fitness',
    cost: 1599,
    currency: '₹',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-12',
    icon: '💪',
    isActive: true,
    startedDate: '2026-03-12',
    paymentMethod: 'HDFC credit card',
    reminderDays: 5,
    notes: 'Gym and group classes membership.',
    website: 'https://www.cult.fit',
  },
];
